# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "zilliqa-devops-dev-state"
    dynamodb_table = "zilliqa-devops-dev-state"
    encrypt        = true
    key            = "services/knote/terraform.tfstate"
    profile        = "zilliqa-infra"
    region         = "eu-west-1"
  }
}
